# Dramatis Personae

## Personae Brydainiae

### Arthur Cadwallader
An aspiring knight of 20 years, seeking martial glory for his scholarly family. Sworn to be Hen Sarum's man.

#### his father Emrys Cadwallader
a bookish recluse, Earl of Porthennor

#### his older brothers Emrys, Carwyn, Bryn
a scholar, a merchant, and a wastrel

#### his elder sister Ceridwen
the wife of Rhodri Gwinwr 7th Earl of Wyth

#### his younger sister Mali
a shy nun with an interest in the mystic

#### his tutor Sir Aled Morglawydd
Master of Arms and veteran of The Long War

#### his uncle Sir Huw Tresco
a wise and kind knight

#### Sergeant Petroc, Tom, Tom, Lorcan, Goch
the garrison of Porthennor, true local men

and Arthur's retainers

#### his squire Owen Tresco
his cousin, well meaning and unassuming

#### Petroc Bryher
a hardened sailor

#### Merlin Merrick
a boy of 12

#### his page Dogmael Porthennor
a beloved orphan

#### his ship's cat Bryn Ddu
adopted as his personal blazon

### Owain ap Ieuan Gradawc
Knight of the Veil. The proud Earl of Hen Sarum. Even handed and level headed.

#### his wife Myfanwy ferch Gwilym Dyrh
a dutiful and shrewd woman

#### his eldest son Gwilym
the august castellan of Hen Sarum

#### his younger sons Hywel, and Cai
infants of 10 and 5 years

#### his elder daughter Agnes "Nest" ferch Owain
wife of Christopher Fitzalan heir to the Duchy of Waerick

#### his younger daughter Mari ferch Owain
an exemplar of etiquette

### Margon Flynn
Baron of Treftone. Died of misadventure at the tournament of Northome.

#### his son Tomos Flynn
failed to avenge his father's honour, scorned

#### his widow Mary Torstall
sister of a deceased Baron, widow of another

### Llewellyn ap Owain o'r Gaer
Earl of Aberiska, Knight of the Veil, elderly and stump-handed. Pacifier of Treftone's rebellion.

#### his son Owain ap Llewellyn o'r Gaer
a capable knight and good fellow

### Caradog Conway
Earl of Cynwy, a grizzled elder

### Gruffudd Sant-Ioan
Duke of Brycheiniog and Constable of Albion, a Knight of the Veil. A fiercely proud man, true to his countrymen.

## Personae Saesiae

### Henry Aberlune
King of Albany, sufferer of an unknown palsy. Upon him the wheel turns.

#### his wife Queen Margot of Valois
daughter of the King of Valois, politically capable

#### his great-uncle Charles
Earl of Aberlune by title, largely infirm with age

### William Fitzalan
Duke of Waerick, Knight of the Veil, dear friend of the King's late father Edward Greymantle. Clear-thinking and merciful.

#### his son Christopher
childhood friend of King Henry and Duke John, lacking malice

### Robert Daubenay
Duke of Uxbridge and Knight of the Veil, a surreptitious politician and close ally of the Queen.

### Robert Hylton
Earl of Rivenhall by birthright, powerful magnate and haughty reveller, despising of his brother

#### his brother William "Wakeful" Hylton
Earl of Nivenhall by decree, slothful and unmindful. Of similar acerbity to his brother. 

### Walter de Hameton
Duke of Hametonshire and Lord Marshal. Dutiful and lacking in humour.

#### his brother Alisaunder de Hameton
Earl of Southome and Lord Admiral, a longsuffering warden

### Nicholas Downes
Lord Mayor of Greatminster and Treasurer of Albany. A witful tongue if not witful mind.

### Sir Dafydd Strangeway
Custodian and knight. Reverent of his holding's ancient past. An unmatched swordsman.

### Osmund Wellsbury
Mayor of Wellsbury and Steward to Duke Walter. Oft overworked and choleric.

### Bishop Richard
Lord Bishop of Winford. Rules by an iron rod.

### Russell Foley
Lord of Speldhall. A well-spoken knight of singular courtoisie.

## Personae Norskaniae

### Sven Sjorefur
Second son of Baron Byggwyk. A duty-bound and penitential knight rising to his station.

#### and his sister Alda Sjorefur
an only daughter with dreams of court. An ingenuous climber

#### her handmaid Hilda
a long-suffering and sardonic tutor

#### his father Gunther
the eponymous Seafox, only recently titled. A master mariner and man-at-arms. Displaced the deceased Baron Henry Torstall

#### his mother Gyda
daughter of a trader from Skadansk, shrewd and mindful of her circumstances

#### his twin Wolfric
heir and wastrel, dedicates to pleasure what his brother dedicates to valour

#### his younger brother Vigo
died at sea at a young age, filling his brothers with guilt

#### his retainer Denis
a veteran of the sea, simple tongued but strong armed

### Harold Thirkell
Earl of Dunhelm and Knight of the Veil. A respected magnate troubled by the uncertain times.

#### his son Rolf Thirkell
childhood friend of Sven Sjorefur, reconciles revelry with respectfulness

#### his sister-in-law Sybil
a well loved and feared widow, a mentor to Alda Sjorefur

### John of Jorvale
Exiled Duke of Jorvale. Measured and statesmanly, his pragmatism created enemies. 

### Eric Sandgate
Earl of Skardaborough. Not outspoken but well-known and respected. 

### Bishop Thomas
Lord Bishop of Lindis and Keeper of the Privy Seal. Pious and a pedant for due process.

### Ralph Ormsby
Earl of Horgrsgate. Quick to temper and sharply legalistic.

### Gunter Foss
Lord of Bjorrton, a charismatic knight and humourist.

### Henry Umber
Knight of Skumasthorp, unrenowned and of poor wealth.

## Personae Pictoniae

### Angus Barra
Chief of Dun Barra, exceedingly tall in both stature and personality. Still settling into his late father's title.

### Murdoch MacNab
Laird Chief of Lothburn and Knight of the Veil. Imperious but not without due support.
